# appveyor.yml
---
environment:
  matrix:
    # Ubuntu - python 3
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: "3.6"
stack: python %PYTHON%

build: off

install:
  - python -m pip install --upgrade pip
  - pip install packaging
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install .

test_script:
  - pytest --cov=gradient_free_optimizers/ -p no:warnings
