# appveyor.yml
---
environment:
  matrix:
    - image: Ubuntu

build: off

install:
  - python -m pip install --upgrade pip
  - pip install packaging
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install .

test_script:
  - pytest --cov=gradient_free_optimizers/ -p no:warnings
